# Build file

name: Build and push docker image

on:
  push:
    tags: ["v**"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PROJECT_NAME: csweb

jobs:
  # job #1
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Step 1
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      # Step 6
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 7
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Build Docker & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            version=${{ steps.tag.outputs.tag }}
          tags: ${{ env.REGISTRY }}/${{ env.REPO }}:${{ steps.tag.outputs.tag }}, ${{ env.REGISTRY }}/${{ env.REPO }}:latest

##########